application: your-appname      # change this to your app-name
version: 1
runtime: python
api_version: 1

handlers:
- url: /resources
  static_dir: resources

- url: /.*
  script: main.py


builtins:
- datastore_admin: on
- appstats: on